# Generated by Django 4.2.4 on 2023-11-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_hotel_room_specialreservation_regularreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='total_quests',
            new_name='total_guests',
        ),
    ]
