-- -- 01. Find Book Titles
-- SELECT
-- 	title
-- FROM
-- 	books
-- WHERE
-- 	SUBSTRING(title, 1, 3) = 'The'
-- ORDER BY
-- 	"id" ASC;
--
--
-- -- 02. Replace Titles
-- SELECT
-- 	REPLACE(title, 'The', '***')
-- FROM
-- 	books
-- WHERE
-- 	left(title, 3) = 'The'
-- ORDER BY
-- 	"id" ASC;
--
--
-- -- 03. Triangles on Bookshelves
-- SELECT
-- 	"id",
-- 	side * height / 2 AS "area"
-- FROM
-- 	triangles
-- ORDER BY
-- 	"id" ASC;
--
--
-- -- 04. Format Costs
-- SELECT
-- 	title,
-- 	ROUND ("cost", 3) AS "modified_price"
-- FROM
-- 	books
-- ORDER BY
-- 	"id" ASC;
--
--
-- -- 05. Year of Birth
-- SELECT
-- 	first_name,
-- 	last_name,
-- 	EXTRACT('year' from born) as "year"
-- FROM
-- 	authors;
--
--
-- -- 06. Format Date of Birth
-- SELECT
-- 	last_name AS "Last Name",
-- 	to_char(born, 'DD (Dy) Mon YYYY') as "Date of Birth"
-- FROM
-- 	authors;
--
--
-- -- 07. Harry Potter Books
-- SELECT
-- 	title
-- FROM
-- 	books
-- WHERE
-- 	title LIKE 'Harry Potter%'
-- ORDER BY
-- 	"id" ASC;
--
