# Generated by Django 4.2.4 on 2023-11-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='fur_color',
            new_name='wing_span',
        ),
    ]
