# Generated by Django 4.2.4 on 2023-11-13 16:16

from django.db import migrations
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_zoodisplayanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='availability',
            field=main_app.models.BooleanChoiceField(default=True),
            preserve_default=False,
        ),
    ]
