# Generated by Django 4.2.4 on 2023-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_veterinarian_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='license_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
