# Generated by Django 4.2.4 on 2023-11-15 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0, 'Rating must be at least 0.00'), django.core.validators.MaxValueValidator(5, 'Rating cannot exceed 5.00')]),
        ),
    ]
