# Generated by Django 4.2.4 on 2023-11-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_migrate_age_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
    ]
