# Generated by Django 4.2.4 on 2023-11-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_hotelroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=20),
        ),
    ]
