# Generated by Django 4.2.4 on 2023-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
